<?php

use Illuminate\Database\Seeder;

class ModulesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('modules')->delete();
        
        \DB::table('modules')->insert(array (
            
            array (
                'id' => 1,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Users',
                'model_name' => 'User',
                'table_name' => 'users',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{first_name}} {{last_name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-users',
                'reporting' => 1,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2016-04-01 09:17:48',
                'updated_at' => '2016-04-01 11:29:51',
            ),
            
            array (
                'id' => 2,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Invitations',
                'model_name' => 'Invitations',
                'table_name' => 'invitations',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{email}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-envelope-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2016-08-18 08:10:56',
                'updated_at' => '2016-08-18 08:10:56',
            ),
            
            array (
                'id' => 3,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Invitation Statuses',
                'model_name' => 'InvitationStatuses',
                'table_name' => 'invitation_statuses',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-list',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2016-08-18 12:18:07',
                'updated_at' => '2016-08-18 12:18:07',
            ),
            
            array (
                'id' => 4,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Assets',
                'model_name' => 'Assets',
                'table_name' => 'assets',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{file_name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-file-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2016-08-30 12:01:17',
                'updated_at' => '2016-08-30 12:01:17',
            ),
            
            array (
                'id' => 5,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Roles',
                'model_name' => 'Roles',
                'table_name' => 'roles',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-user-circle-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2016-09-02 12:24:28',
                'updated_at' => '2016-09-02 12:24:28',
            ),
            
            array (
                'id' => 6,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Permissions',
                'model_name' => 'Permissions',
                'table_name' => 'permissions',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-minus-circle',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2016-09-02 12:43:44',
                'updated_at' => '2016-09-02 12:43:44',
            ),
            
            array (
                'id' => 7,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'File Tags',
                'model_name' => 'FileTags',
                'table_name' => 'file_tags',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-tags',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2016-10-07 07:14:34',
                'updated_at' => '2016-10-07 07:14:34',
            ),
            
            array (
                'id' => 8,
                'category' => 0,
                'type' => 'sortable',
                'name' => 'Widgets',
                'model_name' => 'Widgets',
                'table_name' => 'widgets',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-square',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),
            
            array (
                'id' => 9,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Resized Images',
                'model_name' => 'ResizedImages',
                'table_name' => 'resized_images',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{top_x}},{{top_y}} - {{height}},{{width}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-picture-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2017-06-13 06:41:12',
                'updated_at' => '2017-06-13 06:41:12',
            ),
            
            array (
                'id' => 10,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Image sizes',
                'model_name' => 'ImageSizes',
                'table_name' => 'image_sizes',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-picture-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2017-06-13 06:52:01',
                'updated_at' => '2017-06-13 06:52:01',
            ),
            
            array (
                'id' => 12,
                'category' => NULL,
                'type' => 'multilevel_sortable',
                'name' => 'Galleries',
                'model_name' => 'Galleries',
                'table_name' => 'galleries',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{id}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-camera',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2017-08-20 16:32:56',
                'updated_at' => '2017-08-20 16:32:56',
            ),
            
            array (
                'id' => 13,
                'category' => 12,
                'type' => 'multilevel_sortable',
                'name' => 'Gallery Items',
                'model_name' => 'GalleryItems',
                'table_name' => 'gallery_items',
                'max_depth' => 0,
                'slug' => NULL,
                'anchor_text' => '{{id}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-camera',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 1,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2017-08-20 16:33:27',
                'updated_at' => '2017-08-20 16:33:27',
            ),
            
            array (
                'id' => 14,
                'category' => 0,
                'type' => 'sortable',
                'name' => 'Field Groups',
                'model_name' => 'FieldGroups',
                'table_name' => 'field_groups',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{|findModule}} - {{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-square',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2018-01-10 22:23:31',
                'updated_at' => '2018-01-11 08:18:51',
            ),
            
            array (
                'id' => 32741547385982,
                'category' => NULL,
                'type' => 'single_entry',
                'name' => 'Calendar page',
                'model_name' => 'CalendarPage',
                'table_name' => 'calendar_page',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-calendar',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2019-01-13 13:26:22',
                'updated_at' => '2019-01-13 15:10:38',
            ),
            
            array (
                'id' => 33221547147697,
                'category' => NULL,
                'type' => 'sortable',
                'name' => 'Teams',
                'model_name' => 'Teams',
                'table_name' => 'teams',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-group',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2019-01-10 19:14:57',
                'updated_at' => '2019-01-10 19:18:17',
            ),
            
            array (
                'id' => 33391546380604,
                'category' => NULL,
                'type' => 'single_entry',
                'name' => 'Home page',
                'model_name' => 'HomePage',
                'table_name' => 'home_page',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-home',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2019-01-01 22:10:04',
                'updated_at' => '2019-01-01 22:12:45',
            ),
            
            array (
                'id' => 33761547636374,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'News',
                'model_name' => 'News',
                'table_name' => 'news',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{first_title}} {{second_title}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-newspaper-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2019-01-16 10:59:34',
                'updated_at' => '2019-01-16 16:19:17',
            ),
            
            array (
                'id' => 33771547632908,
                'category' => NULL,
                'type' => 'single_entry',
                'name' => 'Donate page',
                'model_name' => 'DonatePage',
                'table_name' => 'donate_page',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-dollar',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2019-01-16 10:01:48',
                'updated_at' => '2019-01-16 10:01:48',
            ),
            
            array (
                'id' => 33831547148502,
                'category' => NULL,
                'type' => 'single_entry',
                'name' => 'About page',
                'model_name' => 'AboutPage',
                'table_name' => 'about_page',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-info-circle',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2019-01-10 19:28:22',
                'updated_at' => '2019-01-10 20:45:42',
            ),
            
            array (
                'id' => 34431547665054,
                'category' => NULL,
                'type' => 'single_entry',
                'name' => 'Contact',
                'model_name' => 'Contact',
                'table_name' => 'contact',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => NULL,
                'anchor_html' => NULL,
                'icon' => 'fa fa-address-card',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2019-01-16 18:57:34',
                'updated_at' => '2019-01-16 18:57:34',
            ),
            
            array (
                'id' => 34521547146268,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Team seniority',
                'model_name' => 'TeamSeniority',
                'table_name' => 'team_seniority',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-sitemap',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2019-01-10 18:51:08',
                'updated_at' => '2019-01-10 18:51:08',
            ),
            
            array (
                'id' => 34841547387780,
                'category' => NULL,
                'type' => 'non_sortable',
                'name' => 'Games',
                'model_name' => 'Games',
                'table_name' => 'games',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => 'Vs {{opponent.name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-calendar-plus-o',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2019-01-13 13:56:20',
                'updated_at' => '2019-01-13 15:02:50',
            ),
            
            array (
                'id' => 35931546856015,
                'category' => NULL,
                'type' => 'sortable',
                'name' => 'Numbers',
                'model_name' => 'Numbers',
                'table_name' => 'numbers',
                'max_depth' => NULL,
                'slug' => NULL,
                'anchor_text' => '{{name}}',
                'anchor_html' => NULL,
                'icon' => 'fa fa-area-chart',
                'reporting' => 0,
                'lazy_loading' => 0,
                'is_system' => 0,
                'non_grouped_to_bottom' => 0,
                'created_at' => '2019-01-07 10:13:35',
                'updated_at' => '2019-01-07 10:15:00',
            ),
        ));
        
        
    }
}